#!/bin/sh
mdev -s
mkdir /tmp /disk
chmod 777 /tmp
sh /scripts/prepdriver.sh
mdev -s

if [ -b /dev/sda2 ]
then
  ntfs-3g /dev/sda2 /disk -o rw,noatime
else
  ntfs-3g /dev/sda1 /disk -o rw,noatime
fi

if [ -d /disk/WINDOWS ]
then
  reged -IC /disk/WINDOWS/system32/config/software HKEY_LOCAL_MACHINE\\SOFTWARE /scripts/xpsw.reg
  reged -IC /disk/Documents\ and\ Settings/IEUser/NTUSER.DAT HKEY_USERS\\S-1-5-21-776561741-308236825-1417001333-1003 /scripts/xpusr.reg
  cp /scripts/xpvboxga.bat /disk/Documents\ and\ Settings/All\ Users/Start\ Menu/Programs/Startup/
else
  reged -IC /disk/Windows/System32/config/SOFTWARE HKEY_LOCAL_MACHINE\\SOFTWARE /scripts/deuac.reg

  if [ -d /disk/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Startup ]
  then
    cp /scripts/vboxga.bat /disk/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Startup/
  else
    cp /scripts/vboxga.bat /disk/ProgramData/Microsoft/Windows/Start\ Menu/Programs/StartUp/
  fi

  cp /scripts/vsint.cer /disk/vsint.cer
  cp /scripts/reuac.reg /disk/reuac.reg
  cp /scripts/ievms.xml /disk/ievms.xml
  cp /scripts/ievms.bat /disk/ievms.bat
fi
umount /disk 2>/dev/null
poweroff
